### ISSUE TITLE
openttd.cfg

### ISSUE THREAD

**Issue by serofir** [bateau84/openttd#13]
I need a configuration file, at least an example.
I have not found a standard example anywhere.
Nowhere is there information on the detailed configuration of a dedicated server.
All I need, is a standard configuration file, to replace the server name, that's all.
Could you provide a standard configuration file with which this container works out of the box.
So that I can make changes to it by changing the name of the server. I do not need to read the wiki, please do not copy the link to the wiki here. I need a normal example configuration file.

**Comment by bateau84** [comment]
Hey!
yeah, there is no "default" config.
The only config i have is my own, which is full of my own preferences.
I can supply that, but i guess it would be a little useless?

to  change name of the servere you only need to add some stuff under [network] section:
`[network]
commands_per_frame = 2
max_commands_in_queue = 16
bytes_per_frame = 8
bytes_per_frame_burst = 256
pause_on_join = true
server_port = 3979
server_admin_port = 3977
server_admin_chat = true
server_advertise = true
lan_internet = 0
client_name = <server-client-name>
server_password = # optional
rcon_password = <some-password>
admin_password = <some-other-password>
default_company_pass = <some-pass>
server_name = <Server name>
autoclean_novehicles = 12
max_companies = 15
max_clients = 25
max_spectators = 15
restart_game_year = 2500
min_active_clients = 1
server_lang = ANY`
