### ISSUE TITLE
Multi arch builds

### ISSUE THREAD

**Issue by yhaenggi** [bateau84/openttd#15]
Could you build openttd with multi arch manifests for amd64, arm and arm64/aarch64?

**Comment by bateau84** [comment]
Hey!
Yeah, im looking into this. it seems docker plugin on Jenkins not yet supports buildkit (which seems like the easiest way to build multiarch images).

Please let me know if there is simpler ways to solve this :)

**Comment by yhaenggi** [comment]
I tried with buildx/buildkit as well. Seems multi arch is not ready for linux systems... Also the basimage you use dosnt support aarch64. I've created my own build system for it with qemu user.

**Comment by bateau84** [comment]
switched over to ubuntu now. maybe that helps?
