### ISSUE TITLE
Better manual

### ISSUE THREAD

**Issue by samsunix** [bateau84/openttd#19]
Sorry for my stupidity. I have play with m$, linux servers and many different dedicated servers virtualization etc and I have an image in my head how docker works... But I can't get my mind bend over this.

Could you please, please, please provide some basic usage commands and config manual for openttd + docker. 

- Where config files suppose to be
- Where files actually are and how to access them
- How to launch server
- How to stop server

... I just f**** hate all this extra bs around docker. Change my mind. 

[img]https://i.imgur.com/0V09mA3.png[/img]

**Comment by bateau84** [comment]
Hey, i get your point i made some changes to the readme here: https://github.com/bateau84/openttd/blob/better_doc/README.md
could you look it over?

Also i do belive you need to learn docker if you're going to use it, sorry.
I support an image on docker, not docker. So i do take some know-how of docker for granted. 
And the documentation for docker is quite extensive and good. you should check it out :)
https://docs.docker.com/engine/reference/commandline/run/

**Comment by samsunix** [comment]
Looks good! Thank you.
