### ISSUE TITLE
What is a proper way to manage dedicated server openttd.cfg configuration file?

### ISSUE THREAD

**Issue by Thebys** [bateau84/openttd#24]
Hello,
thank you for this great repository, finally an idea attractive and educative enough to get me into Docker. I've read through the available documentation, studied and understood most of the committed files and succeeded in deploying an OpenTTD server using Docker on Ubuntu 18.04 in Azure. (My attempt with Azure Container Instances failed on inability to expose TCP and UDP on 3979 properly so it deployed, but was not reachable)

When I examine the running container I notice an unpleasant lack of openttd.cfg file which I would like to modify. I did not make use of the k8s orchestration yet, the file failed to validate for me, despite some efforts. Also there is -x parameter, preventing config changes to be saved and it seems intentional, why is it? I would be very grateful for some directions on how to manage the config file properly. Thanks in advance.

**Comment by Thebys** [comment]
Ok, this has been discussed previously in closed issues. I'll try to figure it out and update the docs since, well... I am here now.

**Comment by bateau84** [comment]
Hey!
yeah, as mentioned in previous issues you need to mount your openttd.cfg file in to the container with the -v option.
