### ISSUE TITLE
Old download URL in use

### ISSUE THREAD

**Issue by TrueBrain** [bateau84/openttd#28]
Hi!

You are currently using an old URL for OpenTTD downloads here:

https://github.com/bateau84/openttd/blob/6038f23240936a9c0a0fda21172c4e68af5c62a5/prepare.sh#L21

`proxy.binaries.openttd.org` has been replaced with `cdn.openttd.org` a few months back. You already changed this for OpenGFX here:

https://github.com/bateau84/openttd/commit/6038f23240936a9c0a0fda21172c4e68af5c62a5

Possibly a good idea to also change the other to point to `cdn.openttd.org`, as `proxy.binaries.openttd.org` will retire somewhere in the future (it currently redirects you to `cdn.openttd.org`).

https://cdn.openttd.org/openttd-releases/

Contains all official releases ever made by OpenTTD.

Thank you!

PS: if you want to verify cdn.openttd.org is the correct URL: check the download links on https://www.openttd.org/downloads/openttd-releases/latest.html

**Comment by bateau84** [comment]
Thanks for the headsup!
I will change it to the correct URL :)

**Comment by bateau84** [comment]
It is done!
new images are being buildt ( https://github.com/bateau84/openttd/actions/runs/337475288 )
