### ISSUE TITLE
How to generate the openttd.cfg ? And where place it ?

### ISSUE THREAD

**Issue by sebastienvermeille** [bateau84/openttd#3]
Hello I have a problem with this docker container. The documentation talk about a .openttd directory but what about the openttd.cfg ? Should I create it manually ? Where to place it  ?

I tryed to put one on .openttd/openttd.cfg but no effect ...

Thank you in advance for your help :)

**Comment by bateau84** [comment]
Hey!
so, by default there is a user created called "openttd". its home folder i located in /home/openttd.
if you mount your homefolder to this location (-v /home/<youruser>:/home/openttd) you can just create a .openttd folder in your homefolder and copy the openttd.cfg to here.
Hopes this helps :)

**Comment by sebastienvermeille** [comment]
Hey @bateau84 well it doesn't works...

docker run --name openttd -p 3979:3979/tcp -p 3979:3979/udp -v /home/zeus:/home/openttd -e PUID=1000 -e PGID=1000 --detach bateau/openttd:1.6.0

Then I set /home/zeus/.openttd/openttd.cfg
with content :
[gui]
server_name = "My great server"

I also tried to place the file here : /home/zeus/openttd.cfg

it never has any effect. But the server is starting and I can join it. But the config file is not red.

What could be the cause ? Thank you :)

**Comment by bateau84** [comment]
And there is a .openttd folder in your home folder (in /home/zeus)?

**Comment by sebastienvermeille** [comment]
Yes but I had to create it. 

I setted the directory chgrp to docker with xrw-rw-r is it wrong ?

**Comment by bateau84** [comment]
The owner of the dir needs to be the same as the uid and gid you pass with
-e PUID and -e PGID.

man. 27. jun. 2016 kl. 09.42 skrev Sebastien Vermeille <
notifications@github.com>:

**Comment by sebastienvermeille** [comment]
Well so : I run docker from my user "zeus" (1000) which is in group "docker" (1000).

It creates a directory .openttd (user= root group = root) and this folder is empty.

The logs says 
-----------------------------------
GID/UID
-----------------------------------
User uid:    1000
User gid:    1000
User Home:   /home/openttd
-----------------------------------

*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 27
$loadgame ("") not set, starting new game
dbg: [net] Starting dedicated version 1.6.0
dbg: [net] [core] starting network...
dbg: [net] [udp] initializing listeners
dbg: [net] [core] network online, multiplayer available
dbg: [net] Detected broadcast addresses:
dbg: [net] 0) 172.17.0.2
dbg: [net] [udp] closed listeners
dbg: [net] [udp] initializing listeners
dbg: [net] [udp] closed listeners
dbg: [net] [udp] initializing listeners
dbg: [net] starting listeners for clients
dbg: [net] [tcp] listening on IPv4 port 0.0.0.0:3979 (IPv4)
dbg: [net] [tcp] listening on IPv6 port [::]:3979 (IPv6)
dbg: [net] starting listeners for incoming server queries
dbg: [net] [udp] listening on IPv4 port 0.0.0.0:3979 (IPv4)
dbg: [net] [udp] listening on IPv6 port [::]:3979 (IPv6)
dbg: [net] Generating map, please wait...
dbg: [net] Map generation percentage complete: 5
dbg: [net] Map generation percentage complete: 10
dbg: [net] Map generation percentage complete: 15
dbg: [net] Map generation percentage complete: 20
dbg: [net] Map generation percentage complete: 25
dbg: [net] Map generation percentage complete: 30
dbg: [net] Map generation percentage complete: 35
dbg: [net] Map generation percentage complete: 40
dbg: [net] Map generation percentage complete: 45
dbg: [net] Map generation percentage complete: 50
dbg: [net] Map generation percentage complete: 55
dbg: [net] Map generation percentage complete: 60
dbg: [net] Map generation percentage complete: 65
dbg: [net] Map generation percentage complete: 70
dbg: [net] Map generation percentage complete: 75
dbg: [net] Map generation percentage complete: 80
dbg: [net] Map generation percentage complete: 85
dbg: [net] Map generation percentage complete: 90
dbg: [net] Map generation percentage complete: 99
dbg: [net] Map generated, starting game

So I don't really understand what's happening.

**Comment by bateau84** [comment]
If you want to change the users (running openttd inside the container) home folder you can change it with PHOME variable (ex: -e PHOME=/some/other/folder).

Let me give you an example with my setup:
I have on My user (bateau) a .openttd folder in my home folder (/home/bateau/.openttd). I want this folder to be mapped up to the home folder of the user running openttd inside the container (which is named openttd). this means i need to mount /home/bateau/.openttd to /home/openttd/.openttd inside the container. I do this by passing -v in the run command of the container. ex: -v /home/bateau/.openttd:/home/openttd/.openttd.
Sine the user inside the container and my user on the host does not have the same UID and GID, i need to change this inside the container (to get write permissions ex: inside .openttd folder).
i do this by passing -e PUID and -e PGID. you can see your users uid and gid by typing id <your_user>.
