### ISSUE TITLE
Update the latest tag in Docker Hub

### ISSUE THREAD

**Issue by martindzejky** [bateau84/openttd#31]
Hey!

I see that you are using an automated script for generating images for all versions specified in the `releases` file and tagging the appropriate version in docker. It would be helpful if you also tagged the `latest` tag (which is currently some old version) so it would be possible to just run `docker run bateau/openttd` and get the latest OpenTTD.

It should be possible if you just pull the latest release using `head -1 releases` and make a new build which is tagged `latest`. What do you think?

**Comment by bateau84** [comment]
Hey!

Yeah, it seems i missed this when moving from jenkins to github-actions. did'nt notice.
I have corrected it now, i think :)

Thanks for the heads-up!
