### ISSUE TITLE
Provide "load save if present" option

### ISSUE THREAD

**Issue by DJGummikuh** [bateau84/openttd#33]
Hey!

Maybe I'm dumb but...
I'm trying to run an openttd server that I can just spin up (providing an existing openttd.cfg file). I'm expecting it to create a new map if none has been initialized yet but load a savegame if it's already present. I set save_on_exit to 1 in the config and the savegame is written if I initialize the server without -e loadgame but if I provide -e loadgame=exit it expects the file to already be there. That way I will have to recreate the container twice everytime I want to reset the map, surely that can't be the best way?
Help please! :D

**Comment by DJGummikuh** [comment]
Pull Request: https://github.com/bateau84/openttd/pull/34

**Comment by bateau84** [comment]
Merged! :)
