### ISSUE TITLE
My files are under /home/openttd/.local/share/save ? also with env savepath:/home/openttd Portainer

### ISSUE THREAD

**Issue by Trackhe** [bateau84/openttd#36]
My files are under /home/openttd/.local/share/save ? also with env savepath:/home/openttd Portainer
i cant use them with loadgam:last-autosave

**Comment by bateau84** [comment]
Hey! 
Just mount it to that path inside the container with the -v option

**Comment by Trackhe** [comment]
![Bildschirmfoto 2021-04-20 um 21 18 30](https://user-images.githubusercontent.com/1494328/115451898-0ade6e00-a21e-11eb-88ff-9b1956ff7c8e.png)

i guess technicly i have it

**Comment by Trackhe** [comment]
and i dont find any config files.

**Comment by bateau84** [comment]
Hmm, i dont realy know what that is.. but from what i can see, you have to set /home/openttd.local/share/openttd in the volume part

**Comment by Trackhe** [comment]
my volum part is the mount dic on the docker server. and the container the container mounting path

**Comment by bateau84** [comment]
if you dont have config-files in this folder from before, it will be empty. there is no mechanism that will copy files from the container to here.
So these files need to be pressent on your computer before you start the container.

**Comment by Trackhe** [comment]
Unfortunately, that just doesn't work. I build an own image. thank you for your support.
https://github.com/Trackhe/openttd
https://hub.docker.com/repository/docker/trackhe/openttd
