### ISSUE TITLE
Docker image for ARM

### ISSUE THREAD

**Issue by michK** [bateau84/openttd#38]
Hi there,

Any plans to add ARM comparability to the docker container at some point?

Michael

**Comment by bateau84** [comment]
Hey!
Yeah, that would be cool! 
Im not sure how to implement that with my current auto-build setup in Github Actions.
Do you have any ideas? feel free to try to find a good sollution and send a Pull Request! 😄 

I see there are some hacky ways to do it with qemu and such... not sure if i like that solution... 
Buildx seems cleaner. But then i would lose the for-loop to rebuild previous images and get a "fresh and updated" image

**Comment by michK** [comment]
Hi Mats,

Unfortunately I'm not very clued up on either Docker or CI in general, so I don't really have any thoughts at the top of my head.

The reason why I was asking is because I tried running your container on a Raspberry Pi, which didn't work because it uses an ARM CPU.

I was actually able to compile OpenTTD on the Pi quite easily, so I am able to run a dedicated server on it, but I just like the idea of using Docker more (-:

I'll have a look at your auto-build setup and see if anything comes to mind.

Michael

**Comment by bateau84** [comment]
i see.
you could just build it localy on your pi, i think it wil do it with arm then.
Just checkout this repo and do `docker build -t openttd:test .`

This image will then just be available on that Pi and you can then just run it normaly with `docker run -d openttd:latest`
Then just add arguments as needed.

**Comment by michK** [comment]
Great, thank you very much!

**Comment by michK** [comment]
Hi. When I try to do what you suggested, it fails on step 9 with

```
+ [[ ! -e /etc/dpkg/dpkg.cfg.d/docker-apt-speedup ]]
+ echo 'deb http://security.ubuntu.com/ubuntu xenial-security main'
+ apt update -qq

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/binary-armhf/Packages  404  Not Found [IP: 91.189.91.38 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
When I go to `http://security.ubuntu.com/ubuntu/dists/xenial-security/main/`, there is no `binary-armhf` to download, I think that is the problem. Probably because arm is not supported in that repository yet.

Don't worry about it though, I will try to figure it out. Just thought I'd mention it in case you ever revisit this in the future.

 Cheers

**Comment by bateau84** [comment]
So, i actually managed to figure it out how to build with multiple architectures... but i ran into the same problem as you.
seems ubuntu does not have packages available for ARM :(

**Comment by michK** [comment]
O nice. I can think of two possible workarounds.

1) Raspberry pi's by default run on Raspbian, which is based on Debian: https://www.raspbian.org/
2) There is also an Ubuntu build for Raspberry Pi: https://ubuntu.com/raspberry-pi

Do you think it would be able to point the build system to use either one of those when building for ARM?

**Comment by michK** [comment]
Another possibility, though I'm not sure how this will affect your existing workflow, might be to use the docker Ubuntu image which supports all the architectures?
