### ISSUE TITLE
Game saves are going into another folder

### ISSUE THREAD

**Issue by hobbesjaap** [bateau84/openttd#41]
First of all: Thank you so much for creating this!

I'm running your docker file through my Synology and have set user permissions appropriately, etc.

It took me a long time to figure this out, but it seems to be that your server is looking for saves in the path set, but is actually saving them somewhere else for me.

I'm probably doing something wrong, but all save files are being created here:

/home/openttd/.local/share/openttd/save

Using the -v command, I'm connecting /home/openttd/.openttd through Docker. The dedicated server is loading the openttd.cfg file from there perfectly, has populated that folder with all subfolders, but for some reason, all save files are going elsewhere.

**Comment by hobbesjaap** [comment]
I "fixed" it for now by having an "ln" symbolic link running. Which means I can use your Docker image.

I'm also running into the same issue as someone mentioned in the past, where the exit.sav file is completely empty.

**Comment by bateau84** [comment]
Cool!
Closing then :)

**Comment by hobbesjaap** [comment]
I'm not sure if this is a common issue - so the documentation might need to be updated?
