### ISSUE TITLE
Is there a way to change [plane_speed] setting on a multiplayer game?

### ISSUE THREAD

**Issue by elcosomalo1** [bateau84/openttd#42]
Can it be changed? I have a really big map and need to change it since the planes are too slow and don't make any sense.
I know it cannot be changed for multiplayer games, but can it be forced somehow? hacking the save? 

background:
I have a server almost one year old and people playing in it.

**Comment by elcosomalo1** [comment]
Nevermind, just read that I can save the game locally, make the change, then load it in the server.
It would be good if this setting could stay unlocked for the admin though.

**Comment by bateau84** [comment]
Hey!
This repo is for the container only, not the game it self.  
If you have questions regarding the game please direct them to the developers at https://github.com/OpenTTD/OpenTTD
