### ISSUE TITLE
Exit.sav is empty

### ISSUE THREAD

**Issue by hobbesjaap** [bateau84/openttd#43]
Again, really happy with this docker image & thank you for putting it together!

It's working like a dream, but I'm noticing that when the docker container is stopped & restarted, the exit.sav file (autosave function) is 0 bytes. So it seems that the container is shut down before the save file has been generated. Perhaps a longer wait time needs to be built into the shutdown script for this to function? (not sure on how these things work with Docker)

As posted previously, running on a Synology DS216+II

**Comment by bateau84** [comment]
Will look into it.

**Comment by bateau84** [comment]
can you try again with newest image please?

**Comment by bateau84** [comment]
yeah, i do this with runit. https://github.com/bateau84/openttd/blob/master/Dockerfile#L21
it rewrites exit commands to correct signals for openttd to exit properly.

**Comment by bateau84** [comment]
it seems trying to trap SIGKILL is futile... the container is killed imediatly.
do you guys use `docker stop` or `docker kill` to stop the container?
`docker stop` is supposed to send SIGTERM to processses inside the container, which should make openttd exit gracefully
