### ISSUE TITLE
No map generated

### ISSUE THREAD

**Issue by haz-baker** [bateau84/openttd#48]
When launching the container with no previous save the new game created appears as a 0x0 server which cannot be connected to. I'm not sure if i'm just not launching it correctly or if its failing to correctly load the game. When launching i use the command given in the example section of the README

**Comment by bateau84** [comment]
Is this still an issue with latest image?

**Comment by TomSmithThe3rd** [comment]
Can confirm this is still an issue. Giving the container the follwing parameters in a docker compose file:
`version: '3'
services:
  openttd:
    image: bateau/openttd:latest
    container_name: openttd
    environment:
      - loadgame=true
      - savename=worldname.sav
      - PUID=1000
      - PGID=1000
      - debug=1
    ports:
      - 3979:3979
    restart: unless-stopped
    volumes:
      - ./openttd:/home/openttd
#      - ./config:/usr/share/games/openttd/openttd
    networks:
      - public

networks:
  public:
    external: true`

This results in error when trying to boot the container. Cause of error is no .sav named 'worldname.sav' exists.
One must first open up an OpenTTD client, create a save with the name 'worldname.sav, then upload it to the container.

**Comment by bateau84** [comment]
oki. you need to change loadgame to false
