### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by TomSmithThe3rd** [bateau84/openttd#50]
Currently there's a version mismatch when running the latest version of this container and latest version of OpenTTD
Container version: 13.0-RC1
OpenTTD verison: 13.3

**Comment by TomSmithThe3rd** [comment]
> Currently there's a version mismatch when running the latest version of this container and latest version of OpenTTD Container version: 13.0-RC1 OpenTTD verison: 13.3

Edit:
OpenTTD version: 13.4

**Comment by bateau84** [comment]
Updated! :)
