### ISSUE TITLE
Add option for custom config file

### ISSUE THREAD

**Issue by TomSmithThe3rd** [bateau84/openttd#59]
Right now I don't see an option for a custom config file being used, and I see the line `-c "/usr/share/games/openttd/openttd` used throughout the openttd.sh file

Would it be possible to do a variable that enabled a custom config file to be used? Something like `config=true` or `config=<PATH>`?

Please let me know if I'm doing something wrong. I've tried putting the config file in .openttd and in .config/openttd without luck.

**Comment by bateau84** [comment]
you just mount your config folder inside the container to use your custom config.
