### ISSUE TITLE
Docker repo out of date

### ISSUE THREAD

**Issue by SentinelX101** [bateau84/openttd#6]
While the code on this Github repository seems to be up to version 1.6.1 the Docker Hub repo seems to be only on version 1.6.1-RC1 (https://hub.docker.com/r/bateau/openttd/tags/).

When you can could the Docker repo be updated to the latest 1.6.1 build.

Thanks in advance and for the work on the Docker container so far.

**Comment by bateau84** [comment]
Hello! yes, sorry about that. seems there was a smal issue there. it should be pushed to docker hub now :)
