### ISSUE TITLE
Server version mismatch?

### ISSUE THREAD

**Issue by marcus-no** [bateau84/openttd#7]
Hi!

I'm probably doing something wrong, but I get the container up and running, and also can see the server in the game browser when adding it.

But the client lists "Server version: 1.5.3" even though I've tried :latest and :1.6.1
The docker log says "Starting dedicated version 1.6.1"
Any clue what's up?

**Comment by bateau84** [comment]
Hmm. That sounds a bit weird. Maybe its me who taged something wrong during build.
Did you try do set tag to 1.6.1 ? Just to be sure theres not something weird going on.

**Comment by bateau84** [comment]
Hmm. Sorry about that. There seems to be something wrong with my automated build. I have pushed the tag latest and 1.6.1 again now. Can you please try again?

**Comment by marcus-no** [comment]
Works like a charm! Thanks :)
