### ISSUE TITLE
Loading save game

### ISSUE THREAD

**Issue by nobodyshome** [bateau84/openttd#9]
Hi, just wanted to mention that on the docker it's listed as "autosave" for loading the last one. However, in your code on here, it looks like it's actually loading "last-autosave" instead.

**Comment by bateau84** [comment]
Hey! sorry  for det extremly late reply. but this is the intended use. when autosave is passed, you need to set autosave on on your server (in the openttd config).
If you want to just load a savegame you need to set 'loadgame=true' and then 'savegame=<relative-path-to-your-game>'

**Comment by bateau84** [comment]
Changed the doc a bit to explain better (i hope)
